<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
	$pdf->SetMargins(20, 15, 20);
	$title = 'Cetak Form Cuti Karyawan';
	$pdf->SetTitle($title);
	$pdf->AliasNbPages();
	$pdf->AddPage();
	$pdf->SetFont('Arial','UB',18);
	$w = $pdf->GetStringWidth("FORM CUTI");
	$pdf->SetX(($pdf->w -$w)/2);
	$pdf->Cell($w,9,"SURAT PENUGASAN",0,0,'C');
	$pdf->Ln(7);
	$w = $pdf->GetStringWidth("No. ..../FC-HR/..../2017");
	$pdf->SetX(($pdf->w -$w)/2);
	$pdf->SetFont('Arial','',11);
	$pdf->Cell($w,9,"No. ..../FC-HR/..../2017",0,0,'C');
	$pdf->Ln(15);
	$pdf->SetFont('Arial','',11);
	$pdf->MultiCell(0,6,"Dalam rangka melaksanakan tugas mengajar di Cabang ........., kami menugasi:",0,"J");
	$pdf->Ln(5);
	$pdf->Cell(10);
	$pdf->Cell(1,6,"Nama",0,0,"L");
	$pdf->Cell(20);
	$pdf->Cell(2,6,":",0,0,"L");
	$pdf->Cell(2);
	$pdf->Cell(3,6,"Alif Bintoro",0,1,"L");
	$pdf->Cell(10);
	$pdf->Cell(1,6,"Pengajar",0,0,"L");
	$pdf->Cell(20);
	$pdf->Cell(2,6,":",0,0,"L");
	$pdf->Cell(2);
	$pdf->Cell(3,6,"Alif Bintoro",0,1,"L");
	$pdf->Cell(10);
	$pdf->Cell(1,6,"Materi",0,0,"L");
	$pdf->Cell(20);
	$pdf->Cell(2,6,":",0,0,"L");
	$pdf->Cell(2);
	$pdf->Cell(3,6,"Alif Bintoro",0,1,"L");
	$pdf->Cell(10);
	$pdf->Cell(1,6,"Kelas",0,0,"L");
	$pdf->Cell(20);
	$pdf->Cell(2,6,":",0,0,"L");
	$pdf->Cell(2);
	$pdf->Cell(3,6,"Alif Bintoro",0,1,"L");
	$pdf->Cell(10);
	$pdf->Cell(1,6,"Waktu",0,0,"L");
	$pdf->Cell(20);
	$pdf->Cell(2,6,":",0,0,"L");
	$pdf->Cell(2);
	$pdf->Cell(3,6,"Alif Bintoro",0,1,"L");
	$pdf->Ln(5);
	$pdf->Cell(0,6,"Untuk melaksanakan mengajar di kelas dan waktu tersebut di atas.",0,1,"L");
	$pdf->MultiCell(0,6,"Surat penugasan ini disusun untuk dilaksanakan dan setelah selesai dilaksanakan, pengajar segera menyampaikan laporan.",0,"J");
	$pdf->Ln(5);
	$pdf->Cell(0,6,"Surakarta, 27 November 2017",0,1,"R");
	$pdf->Cell(0,6,"Koord pengajar Cabang Surakarta",0,1,"R");
	$pdf->Ln(20);
	$pdf->Cell(0,6,"Alif Bintoro",0,1,"R");
	$pdf->Output("Penugasan_Alif_Bintoro_20112017.pdf","I");