<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
	$pdf->SetMargins(20, 15, 20);
	$title = 'Surat Peringatan '.$jenis;
	$pdf->SetTitle($title);
	$pdf->AliasNbPages();
	$pdf->AddPage();
	$pdf->SetFont('Arial','UB',16);
	$w = $pdf->GetStringWidth("SURAT PERINGATAN ".$jenis);
	$pdf->SetX(($pdf->w -$w)/2);
	$pdf->Cell($w,9,"SURAT PERINGATAN ".$jenis,0,0,'C');
	$pdf->Ln(7);
	$w = $pdf->GetStringWidth("Nomor. ".$surat['nomor_surat']);
	$pdf->SetX(($pdf->w -$w)/2);
	$pdf->SetFont('Arial','',11);
	$pdf->Cell($w,9,"Nomor. ".$surat['nomor_surat'],0,0,'C');
	$pdf->Ln(15);
	$pdf->Cell(0,9,"Kepada : ",0,1,'J');
	$pdf->Cell(10);
	$pdf->Cell(1,6,"Nama",0,0,'L');
	$pdf->Cell(48);
	$pdf->Cell(2,6," : ".$surat['nama'],0,1,'L');
	$pdf->Cell(10);
	$pdf->Cell(1,6,"Jabatan",0,0,'L');
	$pdf->Cell(48);
	$pdf->Cell(2,6," : ".$surat['jabatan'],0,1,'L');
	$pdf->Ln(8);
	$pdf->MultiCell(0,6,$keterangan);
	$pdf->Ln(5);
	$i = 1;
	$alasan = json_decode($surat['alasan']);
	foreach($alasan as $row){
		$pdf->Cell(10);
		$pdf->Cell(1,6,$i.".",0,0,'L');
		$pdf->Cell(8);
		$pdf->MultiCell(0,6,$row);
		$i++;
	}
	$pdf->Ln(5);
	$pdf->MultiCell(0,6,"Demikian surat ini Kami sampaikan dan berlaku selama menjadi karyawan Bimbel Infinity. Kepada yang bersangkutan harap diperhatikan dan diperbaiki dengan segera.");
	$pdf->Ln(10);
	$pdf->Cell(0,6,"Bintaro, ".$surat['tgl'],0,1,"R");
	$pdf->Cell(0,6,"Manager HRO",0,1,"R");
	$pdf->Ln(20);
	$pdf->Cell(0,6,"MN Fitra",0,1,"R");
	$pdf->Output("SuratPeringatan_".$surat['nomor_surat'].".pdf","I");